name: Release

on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
    - name: Build with Gradle
      run: ./gradlew dist --no-daemon
    - name: Deploy distribution package to releases
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/distributions/*.zip  
